Renamed AToken > ALCA/BToken > ALCB
alicenet/alicenet pull request #156
Opened 2022-08-11 12:11 UTC by keirongulrajani

## Scope
- Renamed AToken > ALCA
- Renamed BToken > ALCB
- Refactored interfaces for a/b tokens to staking/utility for improved clarity/maintenance

## Why?

[MP-728](https://madhive.atlassian.net/browse/MP-728)

## Todos

If any, what are the follow-up tasks required other than merging this PR? Have they been arranged?

- [ ] ???

2022-08-11 18:54 UTC, vtleonardo commented on bridge/contracts/ATokenBurner.sol
> +/// @custom:salt StakingTokenBurner
Let's not change the salt for now.

2022-08-11 19:01 UTC, vtleonardo requested changes

2022-08-15 09:13 UTC, keirongulrajani commented on bridge/contracts/ATokenMinter.sol
> +contract ATokenMinter is ImmutableAToken, IStakingTokenMinter {
Though technically it does not need to inherit the interface i believe its more for maintenance purposes as it has clear association with the `IStakingTokenMinter` interface which we refer to when calling the `mint` function elsewhere, so its more to ensure there is no question which contract is the true minter

2022-08-15 09:15 UTC, keirongulrajani commented on bridge/contracts/interfaces/IUtilityToken.sol
> +    struct Deposit {
Good catch! I actually initially removed it from btoken but after reverting some changes to btoken i accidentally reverted this removal too!

2022-08-15 11:28 UTC, vtleonardo commented on bridge/contracts/ATokenMinter.sol
> +contract ATokenMinter is ImmutableAToken, IStakingTokenMinter {
It makes sense! Just make sure that ATokenBurner also inherits its interface for consistency's sake.

2022-08-15 11:29 UTC, vtleonardo commented on bridge/contracts/ATokenBurner.sol
>      constructor() ImmutableFactory(msg.sender) ImmutableAToken() {}
Please, add the inheritance of the IStakingTokenBurner interface here.

2022-08-15 11:32 UTC, vtleonardo commented on bridge/contracts/interfaces/IUtilityToken.sol
> +    struct Deposit {
Can we move the struct to outside the interface?

2022-08-15 11:42 UTC, keirongulrajani commented on bridge/contracts/ATokenMinter.sol
> +contract ATokenMinter is ImmutableAToken, IStakingTokenMinter {
good catch! i thought i did put it there but i guess not, i'll address that now

2022-08-19 22:28 UTC, nelsonhp approved these changes

2022-08-19 22:46 UTC, nelsonhp approved these changes

2022-08-19 22:47 UTC, vtleonardo approved these changes

2022-08-19 22:49 UTC, merged