Add initial documentation refactoring
alicenet/alicenet pull request #218
Opened 2022-08-26 11:32 UTC by vtleonardo

## Scope

Refactor the documentation to be more user friendly :)

2022-09-12 15:51 UTC, diligentis requested changes
Should move `docs/` to wiki, otherwise looking good!

2022-09-12 15:51 UTC, diligentis commented on CONTRIBUTING.md
> +Finally, check the [Forking and submitting your development work](./docs/CREATING_PR.md) to get your work ready for submission.
`docs/` should be move to wiki as we'll likely do a lot of swarming on it there.

2022-09-12 15:51 UTC, diligentis commented on README.md
> +Pre-compiled binaries are available in our [release page](https://github.com/alicenet/alicenet/releases) and instructions on how to build the binary from the source code, can be found in the [Buildin
`docs/` should move to wiki.

2022-09-12 15:51 UTC, diligentis commented on bridge/README.md
>  # AliceNet/Bridge
Just a quick note: I think this is fine for the time being, but we should move `package.json` to the root, at which point we can merge anything needed from this README to the root README as well.

2022-09-12 15:51 UTC, diligentis commented on bridge/README.md
> +All the requisites necessary to run smart contracts are covered on the [Building from source](../docs/BUILD.md) documentation.
`docs/` to wiki.

2022-09-12 15:51 UTC, diligentis commented on bridge/README.md
> +Check the [Testing Documentation](../docs/TESTING.md) for more information on how to run the unit tests for the smart contracts.
`docs/` to wiki.

2022-10-05 20:55 UTC, diligentis commented
@vtleonardo I added build/test/running locally to https://github.com/alicenet/alicenet/wiki

2022-10-14 14:50 UTC, Cr0wn-Gh0ul requested changes
update it

2022-10-14 15:30 UTC, Cr0wn-Gh0ul commented on CONTRIBUTING.md
> +Additionally, if you believe that you've discovered a security vulnerability, you might qualify for our bug bounty program. Visit our [website](https://www.alice.net/) or our [discord server](https:/
https://discord.gg/8esBWyr8h3

2022-10-14 15:35 UTC, diligentis approved these changes
LGTM!

2022-10-14 15:39 UTC, merged

2022-10-14 15:39 UTC, Cr0wn-Gh0ul commented
Follow up with creating configuring node wiki page.