Task name hyphenation + ALCA/ALCB in task names
alicenet/alicenet pull request #250
Opened 2022-09-07 09:58 UTC by keirongulrajani

## Scope

- Updated task names to use hyphenated standard
- Replaced some instances of AToken/BToken with ALCA/ALCB

## Why?

[MP-858](https://madhive.atlassian.net/browse/MP-858)
[MP-858](https://madhive.atlassian.net/browse/MP-859)

## Todos

If any, what are the follow-up tasks required other than merging this PR? Have they been arranged?

- [ ] ???

2022-09-08 14:53 UTC, keirongulrajani commented on bridge/scripts/lib/alicenetFactoryTasks.ts
> +  "full-multi-call-deploy-proxy",
Good catch! looks like it does call that, I'll fix it

2022-09-21 18:24 UTC, z-j-lin requested changes
remove deploymetamorphic from readme

2022-09-21 18:24 UTC, z-j-lin commented on bridge/README.md
> +single metamorphic deployment npx hardhat deploy-metamorphic --contract-name <name>
this is no exists

2022-09-21 18:31 UTC, z-j-lin approved these changes
looks good

2022-09-21 18:41 UTC, vtleonardo approved these changes

2022-09-22 12:18 UTC, merged