Multicall multicontract
alicenet/alicenet pull request #27
Opened 2022-06-29 17:13 UTC by gusjavaz

##Scope
This PR adds two new hardhat tasks:

1. generateContractsDescriptor: Generates a JSON descriptor file with all contract deployment information requirements using (slow) function getBuildInfo (requires deploymentList and deploymentArgsTemplate files to be already generated) . 
2. deployContractsFromDescriptor: Deploy contracts faster with information from previously created JSON file.

##Why?
To speed up contract deployment through deployContracts actual task, tests shows deployContractsFromDescriptor is 5 times faster against hardhat node and almost 2 times faster against geth.

2022-06-29 18:07 UTC, z-j-lin requested changes
dont forget to run npm run lint -- --fix

2022-06-29 18:07 UTC, z-j-lin commented on bridge/scripts/lib/deployment/deploymentUtil.ts
> +              factory,
can get factory address with factory.address

2022-06-30 07:20 UTC, gusjavaz commented on bridge/scripts/lib/deployment/deploymentUtil.ts
> +} from "../../../typechain-types";
Resolved as per ZJ's commit

2022-06-30 07:20 UTC, gusjavaz commented on bridge/scripts/lib/deployment/deploymentUtil.ts
> +  factory: AliceNetFactory,
Resolved as per ZJ's commit

2022-06-30 07:20 UTC, gusjavaz commented on bridge/scripts/lib/deployment/deploymentUtil.ts
> +  const logicContract: ContractFactory = await hre.ethers.getContractFactory(
Resolved as per ZJ's commit

2022-06-30 07:21 UTC, gusjavaz commented on bridge/scripts/lib/deployment/deploymentUtil.ts
> +              factory,
Resolved as per ZJ's commit

2022-07-01 15:49 UTC, z-j-lin approved these changes
all good to go

2022-07-01 17:24 UTC, merged