Bridge Pool ERC20
alicenet/alicenet pull request #277
Opened 2022-09-19 15:33 UTC by gusjavaz

Bridge Pool support for ERC20 assets

2022-09-21 20:18 UTC, z-j-lin requested changes
see comments

2022-09-21 20:18 UTC, z-j-lin commented on bridge/contracts/LocalERC20BridgePoolV1.sol
> +
need a mapping to track used UTXOID

2022-09-21 20:18 UTC, z-j-lin commented on bridge/contracts/LocalERC20BridgePoolV1.sol
> +        UTXO memory burnedUTXO = abi.decode(encodedBurnedUTXO, (UTXO));
need to check if the UTXO has been used

2022-09-21 20:18 UTC, z-j-lin commented on bridge/contracts/utils/ImmutableAuth.sol
> +abstract contract ImmutableCallAny is ImmutableFactory {
what is this for?

2022-11-02 14:03 UTC, gusjavaz commented on bridge/contracts/utils/ImmutableAuth.sol
> +abstract contract ImmutableCallAny is ImmutableFactory {
Removed

2022-11-02 14:03 UTC, gusjavaz commented on bridge/contracts/LocalERC20BridgePoolV1.sol
> +        UTXO memory burnedUTXO = abi.decode(encodedBurnedUTXO, (UTXO));
Done

2022-11-02 14:34 UTC, gusjavaz commented on bridge/contracts/LocalERC20BridgePoolV1.sol
> +
Added

2022-11-02 14:43 UTC, gusjavaz commented
> see comments

All suggestions implemented

2025-09-18 20:36 UTC, closed without merging