Add new estimation method and enforce order of return in the collect functions in the staking contracts
alicenet/alicenet pull request #441
Opened 2022-10-27 19:18 UTC by vtleonardo

This PR:
- Add a new function to estimate the profits and ETH and ALCA in 1 call. 
- Enforce that the eth profit is returned first and the token after in the collect and estimation functions. We are adopting the same order that we use when we burn a position for consistency.

2022-10-27 22:49 UTC, z-j-lin requested changes
add unit tests for new functions

2022-10-27 22:49 UTC, z-j-lin commented on bridge/contracts/libraries/StakingNFT/StakingNFT.sol
> +    function estimateAllProfits(uint256 tokenID_)
add unit test

2022-10-31 13:18 UTC, vtleonardo commented on bridge/contracts/libraries/StakingNFT/StakingNFT.sol
> +    function estimateAllProfits(uint256 tokenID_)
Unit tests added

2022-10-31 14:54 UTC, Cr0wn-Gh0ul reviewed
Change _collect function name to be more correct.

2022-10-31 15:20 UTC, Cr0wn-Gh0ul approved these changes
LGTM

2022-10-31 15:22 UTC, merged