Add new migrateTo method to the ALCA contract
alicenet/alicenet pull request #443
Opened 2022-10-27 19:51 UTC by vtleonardo

## Scope

Add a new method to allow migrating ALCA to a certain address.

2022-10-27 22:46 UTC, z-j-lin requested changes
add test for migrateTo

2022-10-27 22:46 UTC, z-j-lin commented on bridge/contracts/AToken.sol
> +    function migrateTo(address to, uint256 amount) public returns (uint256) {
add unit tests

2022-10-28 17:30 UTC, vtleonardo commented on bridge/contracts/AToken.sol
> +    function migrateTo(address to, uint256 amount) public returns (uint256) {
Test added!

2022-10-31 14:48 UTC, Cr0wn-Gh0ul approved these changes
LGTM

2022-10-31 14:50 UTC, z-j-lin approved these changes
looks good

2022-10-31 14:50 UTC, merged